# Generated by Django 5.0.1 on 2024-01-23 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_p2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='userCreator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectFlashback_b_p2_app.cookieuser'),
        ),
    ]
