# Generated by Django 5.0.1 on 2024-01-29 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_p2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='cookieuser',
            name='requestCount',
        ),
        migrations.RemoveField(
            model_name='globalmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='globalmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='globalmodel',
            name='requestCount',
        ),
        migrations.AddField(
            model_name='cookieuser',
            name='requester_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ProjectFlashback_b_p2_app.requester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalmodel',
            name='requester_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProjectFlashback_b_p2_app.requester'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RequestTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestCount', models.IntegerField(default=0)),
                ('firstRequestTime', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectFlashback_b_p2_app.requester')),
            ],
        ),
    ]
