# Generated by Django 5.0.1 on 2024-01-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_p2_app', '0002_alter_story_usercreator'),
    ]

    operations = [
        migrations.AddField(
            model_name='storystage',
            name='stageTitle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
