# Generated by Django 5.0.1 on 2024-01-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_p2_app', '0003_storystage_stagetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='generatedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
