# Generated by Django 5.0.1 on 2024-01-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_p2_app', '0004_story_generatedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('requestCount', models.IntegerField(default=0)),
            ],
        ),
    ]
