# Generated by Django 5.0.1 on 2024-01-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_p2_app', '0005_globalmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='complete',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
