# Generated by Django 5.0.1 on 2024-01-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectFlashback_b_p2_app', '0007_storystage_imgexists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storystage',
            name='imgExists',
            field=models.BooleanField(),
        ),
    ]
